mod 'carbon',
  :git => 'https://github.com/jtopjian/puppet-carbon'

mod 'stdlib',
  :git => 'https://github.com/puppetlabs/puppetlabs-stdlib'

mod 'inifile',
  :git => 'https://github.com/puppetlabs/puppetlabs-inifile'
